name: Publish the package to the github maven package repository
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
      - '**/.github/workflows/deploy.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Publish to GitHub Packages
        run: gradle -Pversion=${{ github.event.release.tag_name }} build publish
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ github.token }}